## Copyright (C) 2023 Jonathan D. Magasin
##
## This file describes tools required to run the nifH ASV workflow.
## Additionally the tools provided in the DADA2_nifH environment that was
## created during installation of the DADA2 nifH pipeline are required.
## Both environments must be activated in order to use the workflow.
##
## Maintainer caution: Do not add R packages because we want the R installed in
## DADA2_nifH to be used.
##
name: nifH_ASV_workflow
channels:
  - conda-forge
  - defaults
dependencies:
  - make               >=4.3
