## Copyright (C) 2023 Jonathan D. Magasin
##
## This file describes tools required to run the nifH ASV workflow.
## Additionally the tools provided in the DADA2_nifH environment that was
## created during installation of the DADA2 nifH pipeline are required.
## Both environments must be activated in order to use the workflow.
##


## list tools the minimal conda environment for running the DADA2 nifH pipeline (see
## INSTALL.txt).  If you also wish to run ancillary tools, then you must install several additional
## packages (see INSTALL_ancillary.txt).  The pipeline and ancillary tools were developed mainly
## using DADA2 version 1.20.0 (and R v4.1.3).  However, any DADA2 version >=1.20 should be fine,
## including the latest (as of July 15, 2023), v1.28.0 (which requires R >=4.3).
##
name: nifH_ASV_workflow
channels:
  - conda-forge
  - bioconda
  - defaults
 dependencies:
  - make               >=4.3
  - r-lutz             >=0.3.1
